### ISSUE TITLE
Should the Sanity projectID in jungle.config.js be kept private?

### ISSUE THREAD

**Issue by jastuccio** [stordahl/jungle-sanity#2]
using something like dotenv? Does exposing the Sanity projectID (in jungle.config.js) in the repo create any security risks for this project?

[Dot env files (.env) - Sanity.io docs](https://www.sanity.io/docs/studio-environment-variables#dot-env-files-env-f5e9e3158896)

or maybe this is a non-issue?
>[With Sanity, there's no need to authenticate requests to our backend because sanity only allows certain domains to query your content.](https://www.junglejs.org/blog/jungle-sanity/)

**Comment by stordahl** [comment]
When querying Sanity from the front-end, your project ID would be discoverable even if you placed it into a dotenv file. Dotenv shouldn't be used for anything that needs to remain a secret. Because Sanity requires you to define CORS Origins in Settings > API, even if your project ID is exposed, only requests from these defined origins will return data. Hope that makes sense!

**Comment by jastuccio** [comment]
Thank you for the reply! I am considering launching a blog starting from this tutorial 🙂

**Comment by stordahl** [comment]
Let me know how it goes!
